# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: # トリガを設定
  push:
    branches:
      - main
      - develop
#      - feature/**     develop にマージされたときに二重にトリガが走る
    paths-ignore:
      - README.md
      - Docs/**
  pull_request:
    branches:
      - develop # 他の人が push したときにも実行できる
    paths-ignore:
      - README.md
      - Docs/**
# 環境変数の設定
env:
  DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2   # 定義されているアクションを実行できる

      - name: Cache Gems
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundled Gems
        run: make install-bundler
      
      - name: Install Mint
        run: brew install mint
        
      - name: Cache Mint packages
        uses: actions/cache@v2
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-
            
      - name: Install Carthage frameworks
        run: make install-carthage
      
      - name: Generate Xcode project and install Pods
        run: make generate-xcodeproj
    
      - name: Xcode build
        run: make build-debug
      
      - name: Xcode test
        run: make test
